# Default configuration values for my-app
frontend:
  # In the next phase, we will replace this with your Google Artifact Registry URL
  image: us-central1-docker.pkg.dev/gke-multiregion-application/my-repo/frontend:fe1296404bce0de6e2eeed4911fb2639a67881a2
  replicaCount: 2

backend:
  image: us-central1-docker.pkg.dev/gke-multiregion-application/my-repo/backend:fe1296404bce0de6e2eeed4911fb2639a67881a2
  replicaCount: 2

database:
  image: postgres:15-alpine
  user: postgres
  password: secretpassword
  dbName: appdb