# Default configuration values for my-app
frontend:
  # In the next phase, we will replace this with your Google Artifact Registry URL
  image: us-central1-docker.pkg.dev/gke-multiregion-application/my-repo/frontend:bd53d770251498e7695f7f230c37684a6db9489d
  replicaCount: 2

backend:
  image: us-central1-docker.pkg.dev/gke-multiregion-application/my-repo/backend:bd53d770251498e7695f7f230c37684a6db9489d
  replicaCount: 2

database:
  image: postgres:15-alpine
  user: postgres
  password: secretpassword
  dbName: appdb