apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "gce" # Uses GKE's default load balancer
spec:
  rules:
    - http:
        paths:
          # Route /api/ to the Python backend
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: 5000
          # Route everything else to the Nginx frontend
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 80