apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-backend-monitor
  labels:
    release: prometheus # This label is critical! It tells the stack to pick this up.
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s